services:
  jekyll:
    image: jekyll/jekyll:4
    volumes:
      - ./docs:/srv/jekyll
      - ./docs/vendor/bundle:/usr/local/bundle
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --host 0.0.0.0 --livereload --drafts --force_polling --future